version: '3.8'
services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER: INSIDE

  customer-service:
    restart: on-failure
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    #environment:
      #- SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8080:8080'
    depends_on:
        - kafka

  product-service:
    restart: on-failure
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - kafka


